### ISSUE TITLE
大神，是否可以添加对 vue 文件支持呀？

### ISSUE THREAD

**Issue by stuartZhang** [AlloyTeam/AlloyLint#2]
使用您做的工具对 vue 文件格式化时，提示 No file to be fixed

![image](https://user-images.githubusercontent.com/13935927/80053305-336e5200-854f-11ea-827d-5a9034d739c5.png)

**Comment by liqingjht** [comment]
已经这个 commit 上支持 25cddbcc77d2dd82a1cdd2944695156e9d24f36f

并发布版本 0.0.4
